[tool.kedro]
package_name = "linear_regression"
project_name = "Linear Regression"
kedro_init_version = "0.18.8"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/linear_regression -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.kedro.micropkg.pull]
"../../../shared/dist/take_columns-0.2.tar.gz" = {alias="take_columns", destination = "shared"}
"../../../shared/dist/make_info-0.2.tar.gz" = {alias="make_info", destination = "shared"}
"../../../shared/dist/train_test_split-0.2.tar.gz" = {alias="train_test_split", destination = "shared"}
"../../../shared/dist/fold_split-0.1.tar.gz" = {alias="fold_split", destination = "shared"}