[tool.kedro]
package_name = "l2_shared"
project_name = "l2_shared"
kedro_init_version = "0.18.9"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/l2_shared -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.kedro.micropkg.package]
"pipelines.cross_validate"={}
"pipelines.train"={}
"pipelines.regression_analysis"={}
"pipelines.classification_analysis"={}

[tool.kedro.micropkg.pull]
"../shared/dist/fold_split-0.2.tar.gz" = {alias="fold_split", destination = "pipelines/cross_validate"}
"../shared/dist/train_test_split-0.2.tar.gz" = {alias="train_test_split", destination = "pipelines/cross_validate"}