[tool.kedro]
package_name = "shared"
project_name = "shared"
kedro_init_version = "0.18.8"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/shared -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.kedro.micropkg.package]
# SKLearn
"pipelines.sklearn.fold_split"={}
"pipelines.sklearn.train_test_split"={}
"pipelines.sklearn.train_lig_reg"={}
"pipelines.sklearn.train_log_reg"={}
# Pandas
"pipelines.pandas.take_columns"={}
"pipelines.pandas.make_info"={}
"pipelines.pandas.drop_zero_columns"={}